### ISSUE TITLE
Cmus crashing on update or adding music.

### ISSUE THREAD

**Issue by kmkrebs** [cmus/cmus#492]
Hi -- I recently cloned cmus from github and compiled and ran into an error -- whenever I run :update or :a ~/Music, cmus crashes hard.  Here's what shows up in my terminal.  Strangely, I cannot scroll back to see anymore of the error.  Also, I cannot find the core dump from cmus anywhere.

I haven't encountered this problem before, and I've been using cmus compiled from github for upwards of a year.

Any ideas?

```
7f258e90d000-7f258e939000 r-xp 00000000 fd:01 926551                     /usr/lib64/libsoxr.so.0.1.1
7f258e939000-7f258eb38000 ---p 0002c000 fd:01 926551                     /usr/lib64/libsoxr.so.0.1.1
7f258eb38000-7f258eb3a000 r--p 0002b000 fd:01 926551                     /usr/lib64/libsoxr.so.0.1.1
7f258eb3a000-7f258eb3b000 rw-p 0002d000 fd:01 926551                     /usr/lib64/libsoxr.so.0.1.1
7f258eb3b000-7f258eb70000 rw-p 00000000 00:00 0 
7f258eb75000-7f258eb7f000 r-xp 00000000 fd:01 927558                     /usr/lib64/libgsm.so.1.0.12
7f258eb7f000-7f258ed7f000 ---p 0000a000 fd:01 927558                     /usr/lib64/libgsm.so.1.0.12
7f258ed7f000-7f258ed80000 r--p 0000a000 fd:01 927558                     /usr/lib64/libgsm.so.1.0.12
7f258ed80000-7f258ed81000 rw-p 0000b000 fd:01 927558                     /usr/lib64/libgsm.so.1.0.12
7f258ed85000-7f258edcc000 r-xp 00000000 fd:01 918623                     /usr/lib64/libmp3lame.so.0.0.0
7f258edcc000-7f258efcb000 ---p 00047000 fd:01 918623                     /usr/lib64/libmp3lame.so.0.0.0
7f258efcb000-7f258efcd000 r--p 00046000 fd:01 918623                     /usr/lib64/libmp3lame.so.0.0.0
7f258efcd000-7f258efce000 rw-p 00048000 fd:01 918623                     /usr/lib64/libmp3lame.so.0.0.0
7f258efce000-7f258effc000 rw-p 00000000 00:00 0 
7f258effd000-7f258f020000 r-xp 00000000 fd:01 925168                     /usr/lib64/libopenjpeg.so.1.5.1
7f258f020000-7f258f21f000 ---p 00023000 fd:01 925168                     /usr/lib64/libopenjpeg.so.1.5.1
7f258f21f000-7f258f220000 r--p 00022000 fd:01 925168                     /usr/lib64/libopenjpeg.so.1.5.1
7f258f220000-7f258f221000 rw-p 00023000 fd:01 925168                     /usr/lib64/libopenjpeg.so.1.5.1
7f258f225000-7f258f304000 r-xp 00000000 fd:01 927519                     /usr/lib64/libschroedinger-1.0.so.0.11.0
7f258f304000-7f258f503000 ---p 000df000 fd:01 927519                     /usr/lib64/libschroedinger-1.0.so.0.11.0
7f258f503000-7f258f506000 r--p 000de000 fd:01 927519                     /usr/lib64/libschroedinger-1.0.so.0.11.0
7f258f506000-7f258f507000 rw-p 000e1000 fd:01 927519                     /usr/lib64/libschroedinger-1.0.so.0.11.0
7f258f507000-7f258f508000 rw-p 00000000 00:00 0 
7f258f50d000-7f258f524000 r-xp 00000000 fd:01 930620                     /usr/lib64/libspeex.so.1.5.0
7f258f524000-7f258f724000 ---p 00017000 fd:01 930620  [1]    5248 abort (core dumped)  cmus
%    
```
---

1) `uname -a`:
```
Linux finnegan 4.6.4-301.fc24.x86_64 #1 SMP Tue Jul 12 11:50:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.0-153-g6c1cc20
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao
```

**Comment by mahkoh** [comment]
Post a backtrace like this in gdb:

```
thread apply all bt
```

**Comment by mahkoh** [comment]
And please use the latest master.

**Comment by kmkrebs** [comment]
Hi again, I got the traceback in gdb, and it looks like it's a flawed cuesheet that's causing the problem.
Cuesheet follows traceback.  

I noticed in the cuesheet, it's an mp3 file, but in the FILE designation the filename is followed by WAVE.  However, changing it to MP3 still results in a crash...  If I move the directory out of my music path, cmus doesn't crash on update / adding.

This directory & cuesheet have been in my collection since I began using cmus quite some time ago, so whatever is causing the error seems to have been recently introduced.

Thanks for your time and also for cmus!

```
Thread 5 (Thread 0x7fffde858700 (LWP 25130)):
#0  0x00007ffff6b6c32d in poll () from /lib64/libc.so.6
#1  0x00007fffe3bd8981 in poll_func () from /lib64/libpulse.so.0
#2  0x00007fffe3bca161 in pa_mainloop_poll () from /lib64/libpulse.so.0
#3  0x00007fffe3bca7fe in pa_mainloop_iterate () from /lib64/libpulse.so.0
#4  0x00007fffe3bca8b0 in pa_mainloop_run () from /lib64/libpulse.so.0
#5  0x00007fffe3bd88c9 in thread () from /lib64/libpulse.so.0
#6  0x00007fffe397a18b in internal_thread_func () from /usr/lib64/pulseaudio/libpulsecommon-8.0.so
#7  0x00007ffff7bc45ca in start_thread () from /lib64/libpthread.so.0
#8  0x00007ffff6b77ead in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7fffdf20d700 (LWP 25129)):
#0  0x00007ffff6aa96f5 in raise () from /lib64/libc.so.6
#1  0x00007ffff6aab2fa in abort () from /lib64/libc.so.6
#2  0x00007ffff6aea600 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff6af2d4a in _int_free () from /lib64/libc.so.6
#4  0x00007ffff6af62ac in free () from /lib64/libc.so.6
#5  0x00007ffff7142fd8 in track_delete () from /lib64/libcue.so.2.0.1
#6  0x00007ffff714303a in cd_delete () from /lib64/libcue.so.2.0.1
#7  0x00007fffee59fb88 in cue_open (ip_data=0x7fffc802f9a8) at cue.c:170
#8  0x000000000041e101 in ip_open (ip=ip@entry=0x7fffc802f9a0) at input.c:598
#9  0x000000000040d470 in ip_get_ti (
    filename=0x305cd10 "cue:///home/kmkrebs/Music/electronic/The Black Dog/Liber Dogma/01-the_black_dog-liber_dogma.cue/10") at cache.c:411
#10 0x000000000040e259 in cache_refresh (count=count@entry=0x7fffdf20cd7c, force=0) at cache.c:510
#11 0x000000000041fc32 in do_update_cache_job (data=0x35dfbf0) at job.c:524
#12 0x0000000000436977 in worker_loop (arg=<optimized out>) at worker.c:78
#13 0x00007ffff7bc45ca in start_thread () from /lib64/libpthread.so.0
#14 0x00007ffff6b77ead in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7fffdfa0e700 (LWP 25128)):
#0  0x00007ffff7bc9bd0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000427773 in consumer_loop (arg=<optimized out>) at player.c:862
#2  0x00007ffff7bc45ca in start_thread () from /lib64/libpthread.so.0
#3  0x00007ffff6b77ead in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fffe020f700 (LWP 25127)):
#0  0x00007ffff7bc9bd0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000426f67 in producer_loop (arg=<optimized out>) at player.c:965
#2  0x00007ffff7bc45ca in start_thread () from /lib64/libpthread.so.0
#3  0x00007ffff6b77ead in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7f298c0 (LWP 25101)):
#0  0x00007ffff6b6e103 in select () from /lib64/libc.so.6
#1  0x000000000043484e in main_loop () at ui_curses.c:2143
#2  0x000000000040bbd4 in main (argc=<optimized out>, argv=<optimized out>) at ui_curses.c:2465
```

```
REM GENRE Electronic
REM DATE 2011
PERFORMER "The Black Dog"
TITLE "Liber Dogma"
REM REPLAYGAIN_ALBUM_GAIN -5.23 dB
REM REPLAYGAIN_ALBUM_PEAK 1.026247
FILE "01-the_black_dog-liber_dogma.mp3" WAVE
  TRACK 01 AUDIO
    TITLE "Dark Wave Creeping"
    REM REPLAYGAIN_TRACK_GAIN -3.59 dB
    REM REPLAYGAIN_TRACK_PEAK 0.996689
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "The Death Ov The Black Sun"
    REM REPLAYGAIN_TRACK_GAIN -5.42 dB
    REM REPLAYGAIN_TRACK_PEAK 0.986079
    INDEX 01 05:23:01
  TRACK 03 AUDIO
    TITLE "Steam Caliphate"
    REM REPLAYGAIN_TRACK_GAIN -7.47 dB
    REM REPLAYGAIN_TRACK_PEAK 0.992614
    INDEX 01 08:31:13
  TRACK 04 AUDIO
    TITLE "Drop Kick Kali"
    REM REPLAYGAIN_TRACK_GAIN -6.11 dB
    REM REPLAYGAIN_TRACK_PEAK 0.926192
    INDEX 01 11:16:02
  TRACK 05 AUDIO
    TITLE "Eden 353"
    REM REPLAYGAIN_TRACK_GAIN -1.79 dB
    REM REPLAYGAIN_TRACK_PEAK 0.980359
    INDEX 01 14:23:74
  TRACK 06 AUDIO
    TITLE "The Black Maria"
    REM REPLAYGAIN_TRACK_GAIN -4.95 dB
    REM REPLAYGAIN_TRACK_PEAK 1.011542
    INDEX 01 17:58:00
  TRACK 07 AUDIO
    TITLE "Single Light Focus"
    REM REPLAYGAIN_TRACK_GAIN -5.29 dB
    REM REPLAYGAIN_TRACK_PEAK 0.946568
    INDEX 01 22:41:64
  TRACK 08 AUDIO
    TITLE "Silent Escape"
    REM REPLAYGAIN_TRACK_GAIN -5.72 dB
    REM REPLAYGAIN_TRACK_PEAK 0.990129
    INDEX 01 27:51:74
  TRACK 09 AUDIO
    TITLE "Hype Knot 7"
    REM REPLAYGAIN_TRACK_GAIN -5.07 dB
    REM REPLAYGAIN_TRACK_PEAK 0.989307
    INDEX 01 33:31:68
  TRACK 10 AUDIO
    TITLE "Bird Siren"
    REM REPLAYGAIN_TRACK_GAIN -7.02 dB
    REM REPLAYGAIN_TRACK_PEAK 0.975251
    INDEX 01 38:17:10
  TRACK 11 AUDIO
    TITLE "Feeder Rub Out"
    REM REPLAYGAIN_TRACK_GAIN -4.00 dB
    REM REPLAYGAIN_TRACK_PEAK 0.975005
    INDEX 01 43:29:21
  TRACK 12 AUDIO
    TITLE "Worship The Drum"
    REM REPLAYGAIN_TRACK_GAIN -3.15 dB
    REM REPLAYGAIN_TRACK_PEAK 1.026247
    INDEX 01 47:47:64
  TRACK 13 AUDIO
    TITLE "Car Crash Magick"
    REM REPLAYGAIN_TRACK_GAIN -5.27 dB
    REM REPLAYGAIN_TRACK_PEAK 0.995467
    INDEX 01 53:12:61
```

**Comment by mahkoh** [comment]
The cue library recently introduced a bug that caused segfaults. Please update to the latest libcue master and try again.

**Comment by kmkrebs** [comment]
Updated to latest libcue master & the problem is resolved.  Thanks for your help!
